#!/usr/bin/env bash
# Configures ninx to perform a redirection
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
sed -i "22s/listen .*/listen 80" /etc/nginx/sites-enabled/default
ufw allow 'Nginx HTTP'
echo 'Hello World' >> /var/www/html/index.html
redirect="\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/$1";
sed -i " /server_name _;/a ${redirect} permanent;" /etc/nginx/sites-enabled/default
service nginx start
