#!/usr/bin/env bash
# Configures ninx to perform a redirection
apt-get -y update
apt-get -y upgrade
sudo apt-get -y install nginx
sed -i "22s/listen .*/listen 80" /etc/nginx/sites-enabled/default
ufw allow 'Nginx HTTP'
echo 'Hello World' >> /var/www/html/index.html
service nginx start
